import type { Question } from "../types";
import type { AnswerRecord } from "../types";
import { isOpenEnded, scoreQuiz } from "./quiz";

/** Download the interview result as a Markdown report file. */
export function downloadReport(input: {
  questions: Question[];
  answers: AnswerRecord[];
  role?: string;
  difficulty: string;
  date: Date;
}): void {
  const { questions, answers, role, difficulty, date } = input;
  const score = scoreQuiz(answers);
  const byId = new Map(questions.map((q) => [q.id, q]));
  const lines: string[] = [
    `# Interview Report — ${role || "Practice Quiz"}`,
    ``,
    `- Date: ${date.toLocaleString()}`,
    `- Difficulty: ${difficulty}`,
    `- Score: ${score.pct}% (${score.correct}/${score.total} objective correct)`,
    ``,
    `## Answers`,
  ];
  answers.forEach((a, i) => {
    const q = byId.get(a.questionId);
    if (!q) return;
    lines.push(``, `### Q${i + 1}. ${q.question}`, ``, `Your answer: ${a.userAnswer || "(empty)"}`);
    if (!isOpenEnded(q)) {
      lines.push(
        `Result: ${a.correct ? "Correct ✅" : "Incorrect ❌"}`,
        `Correct answer: ${q.correct_answer}`,
        `Explanation: ${q.explanation}`,
        `Tip: ${q.interview_tip}`
      );
    } else if (a.ai) {
      lines.push(
        `AI score: ${a.ai.score}/100 (${a.ai.verdict})`,
        `Did well: ${a.ai.understood || "—"}`,
        `Missing: ${a.ai.missing || "—"}`,
        `Tip: ${a.ai.tip || "—"}`,
        a.ai.stronger_answer ? `Stronger example: ${a.ai.stronger_answer}` : "",
        `Model answer: ${q.ideal_answer}`
      );
    } else {
      lines.push(`AI feedback was unavailable.`, `Model answer: ${q.ideal_answer}`);
    }
  });
  lines.push(``, `Generated by AI Interview Prep — practice, learn, improve.`);
  const blob = new Blob([lines.filter((l) => l !== "").join("\n")], {
    type: "text/markdown",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `interview-report-${date.toISOString().slice(0, 10)}.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
